#! /bin/bash
# vim:foldmethod=marker:foldlevel=0

#############################################
# {{{ Fonctions de gestions généraliste     #
#############################################

which_cmd()
{
    which "${1}" 2>/dev/null || command -v "${1}" 2>/dev/null
}

test_cmd_exist()
{
    which_cmd "${1}" >/dev/null 2>&1 && return 0
    return 1
}

# }}}

####################################
# {{{  Définition des couleurs     #
####################################

NEUTRE="" M_GRAS="" D_SOUL="" F_SOUL="" INVERS="" M__DIM=""

# Vérification de l'existence de la commande tput           #{{{
if test_cmd_exist tput
then
    [[ `tput colors 2>/dev/null` -ge 8 ]] &&
        declare -r NB_COULEURS=`tput colors` || declare -r NB_COULEURS=0

    declare -r NEUTRE="`tput sgr 0`" M_GRAS="`tput bold`" D_SOUL="`tput smul`"
    declare -r F_SOUL="`tput rmul`"  INVERS="`tput rev`"  M__DIM="`tput dim`"
else
    declare -r NB_COULEURS=0
fi

#}}}

# Définition des couleurs                   #{{{
if [[ "${NB_COULEURS}" -gt 0 ]]
then
    declare -r C___NOIR="`tput setaf 0`" C__ROUGE="`tput setaf 1`"
    declare -r C___VERT="`tput setaf 2`" C__JAUNE="`tput setaf 3`"
    declare -r C___BLEU="`tput setaf 4`" C_VIOLET="`tput setaf 5`"
    declare -r C___CYAN="`tput setaf 6`" C__BLANC="`tput setaf 7`"

    declare -r C___INOIR="`tput setaf 8`"  C__IROUGE="`tput setaf 9`"
    declare -r C___IVERT="`tput setaf 10`" C__IJAUNE="`tput setaf 11`"
    declare -r C___IBLEU="`tput setaf 12`" C_IVIOLET="`tput setaf 13`"
    declare -r C___ICYAN="`tput setaf 14`" C__IBLANC="`tput setaf 15`"

    declare -r C_SUR___NOIR="`tput setab 0`" C_SUR__ROUGE="`tput setab 1`"
    declare -r C_SUR___VERT="`tput setab 2`" C_SUR__JAUNE="`tput setab 3`"
    declare -r C_SUR___BLEU="`tput setab 4`" C_SUR_VIOLET="`tput setab 5`"
    declare -r C_SUR___CYAN="`tput setab 6`" C_SUR__BLANC="`tput setab 7`"

    declare -r C_SUR___INOIR="`tput setab 8`" C_SUR__IROUGE="`tput setab 9`"
    declare -r C_SUR___IVERT="`tput setab 10`" C_SUR__IJAUNE="`tput setab 11`"
    declare -r C_SUR___IBLEU="`tput setab 12`" C_SUR_IVIOLET="`tput setab 13`"
    declare -r C_SUR___ICYAN="`tput setab 14`" C_SUR__IBLANC="`tput setab 15`"
else
    # Les couleurs sont mises à vide si tput n'est pas installé
    declare -r C___NOIR="" C__ROUGE="" C___VERT="" C__JAUNE=""
    declare -r C___BLEU="" C_VIOLET="" C___CYAN="" C__BLANC=""

    declare -r C___INOIR="" C__IROUGE="" C___IVERT="" C__IJAUNE=""
    declare -r C___IBLEU="" C_IVIOLET="" C___ICYAN="" C__IBLANC=""

    declare -r C_SUR___NOIR="" C_SUR__ROUGE="" C_SUR___VERT="" C_SUR__JAUNE=""
    declare -r C_SUR___BLEU="" C_SUR_VIOLET="" C_SUR___CYAN="" C_SUR__BLANC=""

    declare -r C_SUR___INOIR="" C_SUR__IROUGE="" C_SUR___IVERT="" C_SUR__IJAUNE=""
    declare -r C_SUR___IBLEU="" C_SUR_IVIOLET="" C_SUR___ICYAN="" C_SUR__IBLANC=""
fi

# }}}

# }}}

#echo "Pour installer avec le support de clipboard installer xorg-dev"

# Fonction affiche_section       #{{{
affiche_section()
{
    declare -r COUL="${1}"
    declare -r t="${2}"
    declare -i largeur=80
    declare -i taille_txt="${#t}"
    largeur=$(( ( largeur - taille_txt ) / 2 ))
    printf "${COUL}"
    eval "printf '%.s ' {1..$largeur}"
    printf "${t}"
    eval "printf '%.s ' {1..$largeur}"
    printf "${NEUTRE}\n"
}

#}}}

printf "\n\n"

if [[ -e "./src/vim" ]]
then
    affiche_section "${C_SUR__JAUNE}${C___NOIR}" "Nettoyage de la compilation précédente"
    make distclean
fi

affiche_section "${C_SUR___VERT}${C___NOIR}" "Configuration de vim"

./configure --with-features=huge \
            --with-compiledby=Asmodee \
            --enable-multibyte \
            --enable-rubyinterp \
            --enable-perlinterp \
            --enable-pythoninterp=yes \
            --enable-cscope --disable-netbeans \
            --enable-gui=auto --with-x --prefix=/usr \
            --enable-fail-if-missing
erreur=$?

if [[ "${erreur}" -eq 0 ]]
then
    affiche_section "${C_SUR___VERT}${C___NOIR}" "Compilation de vim"
    make
fi
