.TH "NOMCOMMANDE" 1 "DATE" "version 1.0" "USER COMMANDS"

.SH NAME
.B NOMCOMMANDE
\-\-\-
Fonctionnalité principal

.SH SYNOPSIS
.\" Structure globale de la commande
.B NOMCOMMANDE
[OPTIONS] [ARGUMENTS]

.SH DESCRIPTION
.PP
Une explication du fonctionnement de la commande.

.SH OPTIONS
.TP
.B \-o
L'explication de l'option.

.SH EXAMPLES
.TP
.EX
l'exemple que l'on veut développer
.EE
Une petite explication de l'exemple

.SH EXIT STATUS
.B 0
La commande s'est exécutée correctement.

.B 101
Une option qui nécessite un argument à été appelée sans arguments.

.B 102
Une option qui n'existe pas à été appelée.

.SH AUTHOR
PIVARD Julien
